### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by Mov305**
### Hi there!

-Added the following requirements

1.  The migration of the four tables with their references.
2.  The database setup.
3.  The images of the created tables.
 
Screenshot dbmigrate

Screenshot users photo

### CODE REVIEW

**Review by Ismailco — COMMENTED** [review]
Hi @Mov305, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, with an old README template, kindly make sure to change the README by using the template provided by microverse, and also make sure the PR title is more descriptive. `setup` doesn't give any context of what the PR is about

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Mov305** [comment]
@Ismailco 
Sorry about that but I have returned to Mircroverse after a long personal break.
Where can I find the new template?

**Comment by Mov305** [comment]
@Ismailco
Sorry about that but I have returned to Mircroverse after a long personal break.
Where can I find the new template?

**Comment by Ismailco** [comment]
@Mov305, Sorry I forgot to include the template in the review
Here is the link: https://github.com/microverseinc/readme-template
Also, you should change the PR title to something more descriptive

**Pull request merged**
